services:
  generate:
    build:
      context: generate
      dockerfile: src/Dockerfile

  generate-dev:
    build:
      context: generate
      dockerfile: tests/Dockerfile
    working_dir: /workspace
    volumes:
      - type: bind
        source: ./generate
        target: /workspace
    command:
      - /bin/bash
      - -lc
      - cmake -S . -B build -G Ninja && cmake --build build && ctest --test-dir build --output-on-failure
